// Styles
import { StyleSheet } from 'react-native';
export const indexStyles = StyleSheet.create({
  postButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: 'white',
    borderRadius: 24,
    padding: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  postButtonText: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  navBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    backgroundColor: 'white',
    borderBottomWidth: 2,
    borderBottomColor: '#1E3A5F',
  },
  navButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
  },
  navButtonText: {
    color: '#1E3A5F',
    fontSize: 30,
    fontWeight: 'bold',
    marginRight: 4,
    fontFamily: 'Avenir', // Use Avenir for a modern, geometric sans-serif look
  },
  polisDisplay: {
    backgroundColor: '#1E3A5F', // Polis blue
    paddingVertical: 8,
    paddingHorizontal: 16,
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    color: 'white',
  },
  polisDisplayText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  signInText: {
    color: '#1E3A5F',
    fontSize: 20,
    fontWeight: 'bold',
    marginRight: 4,
    fontFamily: 'Avenir',
  },

  accountIcon: {
    color: '#1E3A5F',
  },
  searchBoxContainer: {
    position: 'absolute',
    top: 80,
    left: '5%',
    right: '5%',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  searchBoxWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: 30,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#ccc',
    paddingHorizontal: 12,
    backgroundColor: 'white',
  },
  icon: {
    marginRight: 8,
    // tintColor: '#fff',
  },
  searchBox: {
    flex: 1,
    fontSize: 16,
    color: '#000',
  },
  mapPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#e0e0e0',
    borderWidth: 1,
    borderColor: '#ccc',
    overflow: 'hidden',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
    elevation: 0,
  },
  iconImage: {
    width: 30,
    height: 30,
    // borderRadius: 18,

  },
  pinButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: 'white',
    borderRadius: 24,
    padding: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  modalOverlay: {
    position: 'absolute',
    top: 40,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 80,
    backgroundColor: 'transparent',
    zIndex: 200,
    elevation: 200,
  },
  modalContent: {
    width: '90%',
    height: 273,
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -1 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    overflow: 'scroll'
  },
  modalTitle: {
    fontSize: 24,
    color: 'black',
    fontWeight: 'bold',
    marginTop: 10,
    marginLeft: 10,
  },
  link: {
    fontSize: 14,
    color: 'blue',
    textDecorationLine: 'underline',
  },
  triangle: {
    top: -1,
    width: 0,
    height: 0,
    borderLeftWidth: 30,
    borderRightWidth: 30,
    borderBottomWidth: 15,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'white',
    borderRadius: 10,
    transform: [{ rotate: '180deg' }],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -30 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  modalMessage: {
    fontSize: 16,
    color: 'black',
    marginLeft: 10,
  },
  closeButton: {
    position: 'absolute',
    right: -10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
  },
  likeButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  commentButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  picHeader: {
    textDecorationLine: 'underline',
    fontSize: 14,
    color: 'black',
    marginTop: 10,
    marginLeft: 10,
  },
  centerDot: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 16,
    height: 16,
    marginLeft: -8,
    marginTop: -8,
    borderRadius: 8,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: 'black',
    zIndex: 10,
  },
  discoverModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    // backgroundColor: 'rgba(32,32,32,0.85)',
    justifyContent: 'flex-end',
    zIndex: 100,
    elevation: 100,
  },
  discoverModalContent: {
    backgroundColor: 'rgb(30, 58, 95)', // Polis blue with high opacity
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: '70%',
    paddingTop: 10,
  },
  dragHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#ccc',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  discoverContent: {
    flex: 1,
    // paddingHorizontal: 20,
  },
  discoverTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 5,
  },
  discoverSubtitle: {
    fontSize: 16,
    color: '#666',
    marginBottom: 30,
  },
  discoverItem: {
    backgroundColor: '#f8f9fa',
    borderBottomWidth: 1,
    padding: 15,
    // borderRadius: 10,
    // marginBottom: 15,
  },
  discoverItemTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 5,
  },
  discoverItemText: {
    fontSize: 14,
    color: '#666',
  },
  actionButtonContainer: {
    position: 'absolute',
    top: 20,
    left: 130,
    zIndex: 10,
    elevation: 10,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 1, // or use marginBottom on iconButton if gap is not supported
  },

  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#1E3A5F",
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12, // for spacing between buttons
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  calloutContainer: {
    backgroundColor: 'rgba(32,32,32,0.95)',
    borderRadius: 12,
    padding: 14,
    minWidth: 340,
    maxWidth: 340,
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
    zIndex: 50,
  },
  calloutTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  calloutDescription: {
    color: '#bbb',
    fontSize: 14,
    marginBottom: 8,
  },
  customCalloutOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 180,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 50,
    elevation: 50,
    // backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  customCalloutContainer: {
    position: 'relative',
    alignItems: 'center',
  },
  closeCalloutButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  closeCalloutText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
});
