// Styles
import { Text, StyleSheet } from 'react-native';
import { getRandomColor } from '@/functions/getRandomColor';
export const indexStyles = StyleSheet.create({
  postButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: 'white',
    borderRadius: 24,
    padding: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  postButtonText: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
navBar: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  paddingHorizontal: 16,
  backgroundColor: '#fff',
  borderBottomWidth: 2,
  borderBottomColor: '#000',
},

  navButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
  },
  navButtonText: {
    color: '#000',
    fontSize: 30,
    fontWeight: 'bold',
    marginRight: 4,
 fontFamily: 'Koulen_400Regular', // Use Avenir for a modern, geometric sans-serif look
    // textShadowColor: '#000',
    // textShadowOffset: { width: 4, height: 4 },
    // textShadowRadius: 3,
  },
  rightContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 12, // Optional, or use margin on individual items
},
signInText: {
  color: '#000',
  fontSize: 20,
  fontWeight: 'bold',
 fontFamily: 'Koulen_400Regular',
  textShadowColor: '#7e7a7a5d',
  textShadowOffset: { width: 2, height: 3 },
  textShadowRadius: 3,
  textAlign: 'right',
  maxWidth: 160, // Optional: constrain if needed
},
polisDisplay: {
  backgroundColor: getRandomColor(),
  paddingVertical: 2,
  paddingHorizontal: 18,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'flex-start',
  
  borderRightWidth: 2,    // right border width
  borderRightColor: 'black', 
  borderBottomWidth: 2,   // bottom border width
  borderBottomColor: 'black',

  color: '#000',
  textShadowColor: '#000',
  textShadowOffset: { width: 3, height: 3 },
  textShadowRadius: 3,
  zIndex: 200,

  alignSelf: 'flex-start',
},

  profilePicPolis: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 12,
    borderWidth: 2,
    borderColor: '#fff',
    backgroundColor: '#222',
  },
  polisDisplayText: {
    color: '#fff',
    fontSize: 19,
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
 fontFamily: 'Koulen_400Regular',
    
  },
  searchBoxContainer: {
    position: 'absolute',
    top: 80,
    left: '5%',
    right: '5%',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  searchBoxWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: 30,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#ccc',
    paddingHorizontal: 12,
    backgroundColor: 'white',
  },
  icon: {
    marginRight: 8,
    // tintColor: '#fff',
  },
  searchBox: {
    flex: 1,
    fontSize: 16,
    color: '#000',
  },
  mapPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#e0e0e0',
    borderWidth: 1,
    borderColor: '#ccc',
    overflow: 'hidden',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
    elevation: 0,
  },
  cluster: {
    backgroundColor: '#fff',
    borderRadius: 25,
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#333',
  },
  clusterText: {
    fontWeight: 'bold', 
     fontSize: 16, 
    color: '#000',
    // textShadowColor: '#fff200ff',
    // textShadowOffset: { width: 1, height: 1 },
    // textShadowRadius: 0,
  },
  iconImage: {
    width: 30,
    height: 30,
    // borderRadius: 18,

  },
  pinButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: 'white',
    borderRadius: 24,
    padding: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  modalOverlay: {
    position: 'absolute',
    top: 40,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 80,
    backgroundColor: 'transparent',
    zIndex: 200,
    elevation: 200,
  },
  modalContent: {
    width: '90%',
    height: 273,
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -1 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    overflow: 'scroll'
  },
  modalTitle: {
    fontSize: 24,
    color: 'black',
    fontWeight: 'bold',
    marginTop: 10,
    marginLeft: 10,
  },
  link: {
    fontSize: 14,
    color: 'blue',
    textDecorationLine: 'underline',
  },
  triangle: {
    top: -1,
    width: 0,
    height: 0,
    borderLeftWidth: 30,
    borderRightWidth: 30,
    borderBottomWidth: 15,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'white',
    borderRadius: 10,
    transform: [{ rotate: '180deg' }],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -30 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  modalMessage: {
    fontSize: 16,
    color: 'black',
    marginLeft: 10,
  },
  closeButton: {
    position: 'absolute',
    right: -10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
  },
  likeButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  commentButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  picHeader: {
    textDecorationLine: 'underline',
    fontSize: 14,
    color: 'black',
    marginTop: 10,
    marginLeft: 10,
  },
  centerDot: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 16,
    height: 16,
    marginLeft: -8,
    marginTop: -8,
    borderRadius: 8,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: 'black',
    zIndex: 10,
  },
  discoverModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    // backgroundColor: 'rgba(255, 255, 255, 0.85)',
    justifyContent: 'flex-end',
    // zIndex: 100,
    elevation: 100,
    borderColor: 'black',
    borderWidth:2, 
  },
  discoverModalContent: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
        borderColor: 'black',
    borderWidth:3,
    height: '70%',
    paddingTop: 10,
    backgroundColor: 'rgba(255, 255, 255, 1)',
  },
  dragHandle: {
    width: 40,
    height: 2,
    backgroundColor: '#ccc',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 5,
  },
  discoverContent: {
    flex: 1,
    // paddingHorizontal: 20,
  },
  discoverTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 5,
  },
  discoverSubtitle: {
    fontSize: 16,
    color: '#666',
    marginBottom: 30,
  },
  discoverItem: {
    backgroundColor: '#f8f9fa',
    borderBottomWidth: 1,
    padding: 15,
    // borderRadius: 10,
    // marginBottom: 15,
  },
  discoverItemTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 5,
  },
  discoverItemText: {
    fontSize: 14,
    color: '#666',
  },
  actionButtonContainer: {
    position: 'relative',
    top: 60,
    left: 150,
    zIndex: 10,
    elevation: 10,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    alignSelf: 'flex-end',
 // or use marginBottom on iconButton if gap is not supported
  },
iconWrapper1: {
  alignItems: 'center',
},
iconWrapper2: {
  top:85, 
  alignItems: 'center',
},

iconText: {
  position: 'absolute',
  color: '#fff',
  fontSize: 32,
  fontWeight: 'bold',
  fontFamily: 'Koulen_400Regular', // "bleed" into the circle below
  textShadowColor: '#000',
  textShadowOffset: { width: 2, height: 2 },
  textShadowRadius: 2,
  zIndex: 150, 
  alignSelf: 'center',
  textAlign: 'center',
},

iconButton1: {
  position: 'absolute',
  top: 3, 
  width: 50,
  height: 50,
  borderRadius: 25,
  backgroundColor: "#f70d1a",
  alignItems: 'center',
  justifyContent: 'center',
  elevation: 2,
  shadowColor: '#000',
  shadowOpacity: 0.2,
  shadowRadius: 4,
  shadowOffset: { width: 0, height: 2 },
  zIndex: 1, 
  
},

iconButton2: { 
  position: 'absolute',
  top: 3, 
  width: 50,
  height: 50,
  borderRadius: 25,
  backgroundColor: "#5e3a99",
  alignItems: 'center',
  justifyContent: 'center',
  elevation: 2,
  shadowColor: '#000',
  shadowOpacity: 0.2,
  shadowRadius: 4,
  shadowOffset: { width: 0, height: 2 },
},

  calloutContainer: {
    backgroundColor: 'rgba(32,32,32,0.95)',
    borderRadius: 12,
    padding: 14,
    minWidth: 340,
    maxWidth: 340,
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  calloutTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  calloutDescription: {
    color: '#bbb',
    fontSize: 14,
    marginBottom: 8,
  },
  customCalloutOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 180,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 50,
    elevation: 50,
    // backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  customCalloutContainer: {
    position: 'relative',
    alignItems: 'center',
  },
  closeCalloutButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  closeCalloutText: {
    color: 'black',
    fontSize: 14,
    fontWeight: 'bold',
  },
});
